openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8080'
    description: Generated server url
paths:
  '/news/{id}':
    get:
      tags:
        - news-controller
      operationId: getNews
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReponseServeurNews'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReponseServeurErreurErreurNotFound'
    put:
      tags:
        - news-controller
      operationId: updateNews
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/News'
        required: true
      responses:
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReponseServeurString'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ReponseServeurErreurListErreur'
                  - $ref: '#/components/schemas/ReponseServeurErreurErreur'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReponseServeurErreurErreurNotFound'
    delete:
      tags:
        - news-controller
      operationId: deleteNews
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReponseServeurString'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReponseServeurErreurErreurNotFound'
  /news:
    get:
      tags:
        - news-controller
      operationId: getCollectionNews
      parameters:
        - name: page
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageNews'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ReponseServeurErreurListErreur'
                  - $ref: '#/components/schemas/ReponseServeurErreurErreur'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReponseServeurErreurErreurNotFound'
    post:
      tags:
        - news-controller
      operationId: createNews
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/News'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReponseServeurNews'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ReponseServeurErreurListErreur'
                  - $ref: '#/components/schemas/ReponseServeurErreurErreur'
  /news/last:
    get:
      tags:
        - news-controller
      operationId: getLastNews
      parameters:
        - name: sort
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Sort'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReponseServeurListNews'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ReponseServeurErreurListErreur'
                  - $ref: '#/components/schemas/ReponseServeurErreurErreur'
  /news/first:
    get:
      tags:
        - news-controller
      operationId: getFirstNews
      parameters:
        - name: sort
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Sort'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReponseServeurListNews'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ReponseServeurErreurListErreur'
                  - $ref: '#/components/schemas/ReponseServeurErreurErreur'
  /news/count:
    get:
      tags:
        - news-controller
      operationId: getCountNews
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReponseServeurLong'
components:
  schemas:
    Erreur:
      type: object
      properties:
        champ:
          type: string
          example: "datePublication"
        message:
          type: string
          example: "Invalid value : -02-19T13:44:35"
    ErreurNotFound:
      type: object
      properties:
        champ:
          type: string
          example: "id"
        message:
          type: string
          example: "NotFound : 4"
    ReponseServeurErreurErreur:
      type: object
      properties:
        erreur:
          $ref: '#/components/schemas/Erreur'
    ReponseServeurErreurErreurNotFound:
      type: object
      properties:
        erreur:
          $ref: '#/components/schemas/ErreurNotFound'
    ReponseServeurErreurListErreur:
      type: object
      properties:
        erreur:
          type: array
          items:
            $ref: '#/components/schemas/Erreur'
    News:
      required:
        - datePublication
      type: object
      properties:
        id:
          type: integer
          format: int64
        datePublication:
          type: string
          format: date-time
        resume:
          minLength: 1
          type: string
          example: "930 nouveaux cas de Covid-19"
        contenu:
          minLength: 10
          type: string
          example: "Le 12 fevrier 2020 le ministère de la santé ..."
    ReponseServeurString:
      type: object
      properties:
        payload:
          type: string
    ReponseServeurNews:
      type: object
      properties:
        payload:
          $ref: '#/components/schemas/News'
    Pageable:
      type: object
      properties:
        page:
          minimum: 0
          type: integer
          format: int32
        size:
          minimum: 1
          type: integer
          format: int32
        sort:
          type: array
          items:
            type: string
            example: 'contenu,datePublication'
    PageNews:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/News'
        number:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/Sort'
        first:
          type: boolean
        last:
          type: boolean
        numberOfElements:
          type: integer
          format: int32
        pageable:
          $ref: '#/components/schemas/Pageable'
        empty:
          type: boolean
    Sort:
      type: object
      properties:
        sort:
          type: array
          items:
            type: string
            example: 'contenu,datePublication'
    ReponseServeurListNews:
      type: object
      properties:
        payload:
          type: array
          items:
            $ref: '#/components/schemas/News'
    ReponseServeurLong:
      type: object
      properties:
        payload:
          type: integer
          format: int64
          example: 17
